# ignore Gemfile.lock
AllCops:
    TargetRubyVersion: 3.0.4
    Exclude:
        - "Gemfile.lock"
        - "Gemfile"

# indentation with 4 spaces
Style/IndentationWidth:
    Width: 4

# bloc

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
    EnforcedStyle: same_line

Layout/EndAlignment:
    EnforcedStyleAlignWith: variable
